# Generated by Django 2.2.7 on 2019-11-08 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, null=True, verbose_name="Telefon"),
                ),
                ("street", models.CharField(max_length=100, verbose_name="Ulice")),
                ("city", models.CharField(max_length=100, verbose_name="Obec")),
                ("zip_code", models.CharField(max_length=10, verbose_name="PSČ")),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("other", "--jiný--"),
                            ("cz", "Česko"),
                            ("sk", "Slovensko"),
                        ],
                        max_length=10,
                        verbose_name="Stát",
                    ),
                ),
                ("school", models.CharField(max_length=80, verbose_name="Škola")),
                (
                    "school_year",
                    models.CharField(
                        choices=[
                            ("4", "4"),
                            ("3", "3"),
                            ("2", "2"),
                            ("1", "1"),
                            ("l", "nižší"),
                        ],
                        max_length=1,
                        verbose_name="Ročník",
                    ),
                ),
                (
                    "school_alt_name",
                    models.CharField(
                        max_length=80, null=True, verbose_name="Název školy"
                    ),
                ),
                (
                    "school_alt_street",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Ulice školy"
                    ),
                ),
                (
                    "school_alt_city",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Obec školy"
                    ),
                ),
                (
                    "school_alt_zip_code",
                    models.CharField(
                        max_length=10, null=True, verbose_name="PSČ školy"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
