# Generated by Django 2.2.7 on 2019-11-11 07:37

import django.db.models.deletion
from django.db import models, migrations

import ksicht.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={"verbose_name": "Účastník", "verbose_name_plural": "Účastníci"},
        ),
        migrations.AddField(
            model_name="participant",
            name="applications",
            field=models.ManyToManyField(
                related_name="participants", to="core.Grade", verbose_name="Přihlášky"
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="end_date",
            field=models.DateField(
                db_index=True,
                default=ksicht.core.models.default_grade_end,
                verbose_name="Končí",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="start_date",
            field=models.DateField(
                db_index=True,
                default=ksicht.core.models.default_grade_start,
                verbose_name="Začíná",
            ),
        ),
        migrations.AlterField(
            model_name="gradeseries",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series",
                to="core.Grade",
                verbose_name="Ročník",
            ),
        ),
    ]
