# Generated by Django 2.2.7 on 2019-11-21 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ('-end_date',), 'verbose_name': 'Ročník', 'verbose_name_plural': 'Ročníky'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Řešitel', 'verbose_name_plural': 'Řešitelé'},
        ),
        migrations.AlterModelOptions(
            name='tasksolutionsubmission',
            options={'permissions': (('change_solution_submission_presence', 'Úprava stavu odevzdání řešení'),), 'verbose_name': 'Odevzdané řešení', 'verbose_name_plural': 'Odevzdaná řešení'},
        ),
        migrations.AlterField(
            model_name='tasksolutionsubmission',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_submissions', to='core.GradeApplication', verbose_name='Přihláška'),
        ),
        migrations.AlterField(
            model_name='tasksolutionsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='rocniky/reseni/', verbose_name='Soubor s řešením'),
        ),
        migrations.AlterField(
            model_name='tasksolutionsubmission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solution_submissions', to='core.Task', verbose_name='Úloha'),
        ),
    ]
