# Generated by Django 2.2.7 on 2019-11-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("series", "nr"),
                "permissions": (("solution_export", "Export odevzdaných úloh"),),
                "verbose_name": "Úloha",
                "verbose_name_plural": "Úlohy",
            },
        ),
    ]
