# Generated by Django 2.2.10 on 2020-06-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0024_flatpagemeta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sticker',
            options={'ordering': ('nr', 'title'), 'verbose_name': 'Nálepka', 'verbose_name_plural': 'Nálepky'},
        ),
        migrations.AlterField(
            model_name='task',
            name='nr',
            field=models.CharField(choices=[('1', '1.'), ('2', '2.'), ('3', '3.'), ('4', '4.'), ('5', '5.')], db_index=True, max_length=1, verbose_name='Číslo úlohy'),
        ),
    ]
