# Generated by Django 2.2.7 on 2019-11-24 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191124_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeapplication',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.Grade'),
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Název')),
                ('nr', models.PositiveSmallIntegerField(db_index=True, verbose_name='Číslo')),
                ('uses', models.ManyToManyField(blank=True, related_name='stickers', to='core.GradeApplication')),
            ],
            options={
                'verbose_name': 'Nálepky',
            },
        ),
    ]
