# Generated by Django 2.2.7 on 2019-11-21 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191121_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksolutionsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Datum nahrání'),
            preserve_default=False,
        ),
    ]
