# Generated by Django 2.2.15 on 2021-11-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20200815_1351"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasksolutionsubmission",
            name="file_for_export_duplex",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="rocniky/reseni-pro-export/",
                verbose_name="Soubor s řešením připravený pro export (s duplexem)",
            ),
        ),
        migrations.AddField(
            model_name="tasksolutionsubmission",
            name="file_for_export_normal",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="rocniky/reseni-pro-export/",
                verbose_name="Soubor s řešením připravený pro export (bez duplexu)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
