# Generated by Django 2.2.7 on 2020-01-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20191124_2029"),
    ]

    operations = [
        migrations.AddField(
            model_name="sticker",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Popis"),
        ),
    ]
