# Generated by Django 2.2.7 on 2020-01-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sticker_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sticker",
            options={
                "permissions": (
                    ("auto_assign_stickers", "Automatické nastavení nálepek"),
                ),
                "verbose_name": "Nálepky",
            },
        ),
    ]
