# Generated by Django 2.2.15 on 2022-03-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211121_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeapplication',
            name='participant_current_grade',
            field=models.CharField(max_length=10, null=True, verbose_name='Ročník'),
        ),
    ]
