# Generated by Django 2.2.8 on 2020-01-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20200118_1115"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sticker",
            options={
                "permissions": (
                    ("auto_assign_stickers", "Automatické nastavení nálepek"),
                ),
                "verbose_name": "Nálepka",
                "verbose_name_plural": "Nálepky",
            },
        ),
        migrations.AddField(
            model_name="sticker",
            name="handpicked",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Přiřazován ručně"
            ),
        ),
    ]
