# Generated by Django 2.2.15 on 2022-03-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gradeapplication_participant_current_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeapplication',
            name='participant_current_grade',
            field=models.CharField(max_length=1, null=True, verbose_name='Ročník'),
        ),
    ]
