# Generated by Django 2.2.8 on 2020-01-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20200118_1519"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasksolutionsubmission",
            name="stickers",
            field=models.ManyToManyField(
                blank=True, related_name="solution_uses", to="core.Sticker"
            ),
        ),
    ]
