# Generated by Django 2.2.15 on 2022-03-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220311_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeapplication',
            name='participant_current_grade',
            field=models.CharField(max_length=10, null=True, verbose_name='Ročník'),
        ),
    ]
