# Generated by Django 2.2.15 on 2023-05-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_auto_20230509_0926"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Jméno")),
                ("bio", models.TextField(verbose_name="Krátké představení")),
                (
                    "image",
                    models.ImageField(
                        help_text="Použijte čtvercový formát",
                        upload_to="lide/",
                        verbose_name="Obrázek",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Čím nižší, tím dříve v seznamu.",
                        verbose_name="Pořadí",
                    ),
                ),
            ],
            options={
                "verbose_name": "Člen KSICHT týmu",
                "verbose_name_plural": "Členové KSICHT týmu",
                "ordering": ("order",),
            },
        ),
    ]
