# Generated by Django 2.2.17 on 2023-09-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_teammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="brochures_by_mail",
            field=models.BooleanField(
                default=True, verbose_name="Zasílat brožury poštou"
            ),
        ),
    ]
