# Generated by Django 2.2.15 on 2022-03-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220313_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeapplication',
            name='participant_current_grade',
            field=models.CharField(max_length=1000, null=True, verbose_name='Ročník'),
        ),
    ]
