# Generated by Django 2.2.8 on 2020-01-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_auto_20200123_1557"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sticker",
            name="nr",
            field=models.PositiveSmallIntegerField(
                db_index=True, unique=True, verbose_name="Číslo"
            ),
        ),
    ]
