# Generated by Django 2.2.8 on 2020-01-24 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_auto_20200124_0958"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gradeseries",
            options={
                "ordering": ("grade", "series"),
                "permissions": (
                    ("series_envelopes_printout", "Export obálek s řešením"),
                ),
                "verbose_name": "Série",
                "verbose_name_plural": "Série",
            },
        ),
        migrations.AddField(
            model_name="gradeapplication",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Datum vytvoření",
            ),
            preserve_default=False,
        ),
    ]
