# Generated by Django 2.2.8 on 2020-01-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_auto_20200124_1106"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gradeseries",
            options={
                "ordering": ("grade", "series"),
                "permissions": (
                    (
                        "series_task_envelopes_printout",
                        "Export obálek pro školy se zadáním",
                    ),
                    ("series_solution_envelopes_printout", "Export obálek s řešením"),
                ),
                "verbose_name": "Série",
                "verbose_name_plural": "Série",
            },
        ),
        migrations.AlterField(
            model_name="participant",
            name="school",
            field=models.CharField(
                choices=[("--jiná--", "-- jiná --")],
                max_length=80,
                verbose_name="Škola",
            ),
        ),
    ]
