# Generated by Django 2.2.10 on 2020-05-24 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_auto_20200524_0845"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventattendee", options={"ordering": ("signup_date",)},
        ),
        migrations.AddField(
            model_name="eventattendee",
            name="signup_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Bude využito při vyhodnocování náhradníků.",
                verbose_name="Datum přihlášky",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eventattendee",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Event",
                verbose_name="Akce",
            ),
        ),
        migrations.AlterField(
            model_name="eventattendee",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Účastník",
            ),
        ),
        migrations.AlterModelTable(name="eventattendee", table=None,),
    ]
