# Generated by Django 2.2.10 on 2020-05-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("flatpages", "0001_initial"),
        ("core", "0023_auto_20200524_0858"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlatPageMeta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Titulek"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Oddělujte čárkou",
                        max_length=150,
                        verbose_name="Klíčová slova",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Krátký popis"),
                ),
                (
                    "allowed_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Pokud zde něco zvolíte, stránka bude dostupná pouze pro uvedené skupiny. Pokud chcete nechat stránku dostupnou pro řešitele, nevyplňujte zde nic.",
                        to="auth.Group",
                        verbose_name="Povoleno pro tyto skupiny",
                    ),
                ),
                (
                    "flatpage",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="flatpages.FlatPage",
                        verbose_name="Stránka",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metadata statické stránky",
                "verbose_name_plural": "Metadata statických stránek",
            },
        ),
    ]
